Develop
Truel0ve/java-filmorate pull request #18
Opened 2023-03-07 16:38 UTC by Truel0ve

2023-03-07 19:03 UTC, EvgenyKoptubenko commented
Почему-то показывает ошибку 
Merging is blocked
The base branch does not allow updates. [Learn more about protected branches.](https://docs.github.com/articles/about-protected-branches/)

2023-03-07 19:07 UTC, EvgenyKoptubenko commented
Если отправить такой запрос
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"nameItem",
	"email":"email23ы2фsы322ц222ы2@email.com",
  "login":"login",
	"birthday":"2021-01-01"
}'
То приходит сообщение об ошибке
{
	"error": "class org.springframework.dao.DataIntegrityViolationException: Неверный формат данных, проверьте корректность передаваемых параметров"
}

Можешь добавить сюда больше информации, чтобы было понятно какие конкретно данные не верны? Если есть желание

2023-03-07 19:08 UTC, EvgenyKoptubenko commented
Если отправить неверного пользователя, то приходит очень длинное сообщение об ошибке
{
	"error": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controllers.UserController.postUser(ru.yandex.practicum.filmorate.model.User) with 2 errors: [Field error in object 'user' on field 'email': rejected value [email3email.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@77f4c379,.*]; default message [must be a well-formed email address]] [Field error in object 'user' on field 'birthday': rejected value [null]; codes [NotNull.user.birthday,NotNull.birthday,NotNull.java.time.LocalDate,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.birthday,birthday]; arguments []; default message [birthday]]; default message [must not be null]] "
}
Можно ли его сократить?

2023-03-07 19:10 UTC, EvgenyKoptubenko commented
Если такой запрос отправить 
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"nameItem",
	"email":"email23ы2фsы322ц222ы2@email.com",
  "login":"login",
	"birthday":"01-01-2001"
}'
То приходит 500-я ошибка
{
	"error": "JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String \"01-01-2001\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '01-01-2001' could not be parsed at index 0; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String \"01-01-2001\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '01-01-2001' could not be parsed at index 0\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 5, column: 13] (through reference chain: ru.yandex.practicum.filmorate.model.User[\"birthday\"])"
}

2023-03-07 19:18 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>              throw new NullPointerException("ID фильма не задан или отсутствует в базе.");
кидать Unchecked Exception не хорошая практика. Лучше создать свой

2023-03-07 19:18 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getRecommendations(Long userId) {
Этот метод нигде не используется

2023-03-07 19:19 UTC, EvgenyKoptubenko requested changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Молодцы, что сделали тесты, обработку ошибок через Advice, batchUpdate. Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий. У вас получились отличные запросы к таблицам.

2023-03-07 21:39 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>              throw new NullPointerException("ID фильма не задан или отсутствует в базе.");
Исправлено во всех классах на ArgumentNotFoundException.

2023-03-07 21:40 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getRecommendations(Long userId) {
Убрал неиспользуемые методы.

2023-03-07 21:49 UTC, Truel0ve commented
Ошибка Merging is blocked была в связи с установленным запретом на внесение изменений в главную ветку. Сейчас ограничение снято.
Оптимизировали вывод сообщений об исключениях в ExceptionController и исправили остальные замечания.

2023-03-08 19:51 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-03-09 06:13 UTC, merged