Add friends likes
Truel0ve/java-filmorate pull request #4
Opened 2023-01-05 18:23 UTC by Truel0ve

2023-01-05 20:54 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        logRequestMethod(RequestMethod.GET);
Если попробовать добавить еще одного такого же пользователя, то падает. Клиент получает 500 ошибку, при этом в теле написано 200 ок
r.y.p.f.controllers.ExceptionController  : 200 OK

org.springframework.web.server.ResponseStatusException: 200 OK
	at ru.yandex.practicum.filmorate.storage.classes.InMemoryUserStorage.createUser(InMemoryUserStorage.java:26) ~[classes/:na]
	at ru.yandex.practicum.filmorate.service.UserService.createUser(UserService.java:28) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controllers.UserController.postUser(UserController.java:34)

2023-01-05 20:55 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        logRequestMethod(RequestMethod.GET);
Такой же ответ приходит при создании дублирующего фильма

2023-01-05 20:57 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        logRequestMethod(RequestMethod.POST);
Если отправить неверную дату фильма, то клиент не видит из-за чего возникла ошибка

ru.yandex.practicum.filmorate.exceptions.ValidationException: Дата релиза не может быть раньше 28 декабря 1895 года.
	at ru.yandex.practicum.filmorate.validators.FilmValidator.validateReleaseDate(FilmValidator.java:45) ~[classes/:na]
	at ru.yandex.practicum.filmorate.validators.FilmValidator.validate(FilmValidator.java:15) ~[classes/:na]
	at ru.yandex.practicum.filmorate.service.FilmService.createFilm(FilmService.java:28) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controllers.FilmController.post(FilmController.java:37)

Клиенту приходит просто 500:
{
	"timestamp": "2023-01-05T20:55:48.564+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}

Но если клиент прислал неверные данные, то должен быть все-таки BadRequest

2023-01-05 20:58 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "^\\w+@\\w+\\.\\w+$")
Попробуй использовать аннотацию @Email - в ней должен быть зашит нужный паттерн

2023-01-05 21:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void addLike(@PathVariable("id") Long filmId, @PathVariable Long userId) {
Желательно добавить проверки вводных данных http://localhost:8080/films/1/like/aaa
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "aaa"

2023-01-05 21:01 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. совсем немного замечаний

2023-01-06 00:47 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        logRequestMethod(RequestMethod.GET);
Исправил, теперь бросает ValidationException("Пользователь с E-mail " + user.getEmail() + " уже есть в базе.") и ValidationException("Фильм \"" + film.getName() + "\" уже есть в базе.")

2023-01-06 00:49 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        logRequestMethod(RequestMethod.POST);
Исправил, теперь возвращает "error": "Дата релиза не может быть раньше 28 декабря 1895 года." и BadRequest.

2023-01-06 00:49 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "^\\w+@\\w+\\.\\w+$")
Поменял, всё работает.

2023-01-06 01:02 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void addLike(@PathVariable("id") Long filmId, @PathVariable Long userId) {
Добавил MethodArgumentTypeMismatchException.class в value метода класса ExceptionController.
Изначально хотел сделать, как показано вот [здесь](https://struchkov.dev/blog/spring-boot-validation/), но при добавлении проверки переменных пути и параметров запроса через @Min(1) несколько тестов Постмана перестают работать.

2023-01-06 14:21 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-19 12:40 UTC, merged