Add database
Truel0ve/java-filmorate pull request #5
Opened 2023-02-18 13:22 UTC by Truel0ve

2023-02-18 19:36 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        Film film = jdbcTemplate.query(sqlSelectFilm, new FilmRowMapper(), filmId).stream()
Попробуй сделать из трех запросов один

2023-02-18 19:37 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                .orElseThrow(() -> new NullPointerException("Фильм с ID=" + filmId + " отсутствует в базе"));
Лучше создать свой собственный эксепшн, чем кидаться Unchecked эксепшенами

2023-02-18 19:40 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Override
Этот компаратор не возвращает 0 для идентичных объектов

2023-02-18 19:44 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/GenreDbStorage.java
> +                    "INSERT INTO genre_list (genre_id, film_id) " +
попробуй переписать на batch insert, чтобы не обращаться к базе данных в for, а сделать это один раз

2023-02-18 19:46 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            String sqlSelectName =
Попробуй обойтись одним запросом, а не select, а потом insert

2023-02-18 19:48 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                jdbcTemplate.update(sqlDeleteFilm, film.getId());
Почему при обновлении фильма удаляются жанры, а при удалении фильма жанры не удаляются?

2023-02-18 19:52 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то падает с 500-й ошибкой
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"nameItem",
	"email":"email232фы322ц222ы2@email.com",
  "login":"login",
	"birthday":"2021-01-01"
}'

PreparedStatementCallback; Check constraint violation: "CONSTRAINT_4D4: "; SQL statement:
INSERT INTO users (email, login, name, birthday) VALUES (?, ?, ?, ?) [23513-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Check constraint violation: "CONSTRAINT_4D4: "; SQL statement:
INSERT INTO users (email, login, name, birthday) VALUES (?, ?, ?, ?) [23513-214]

2023-02-18 19:53 UTC, EvgenyKoptubenko commented
Если отправить запрос с неверным email, то приходит слишком длинное сообщение об ошибке

{
	"error": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controllers.UserController.postUser(ru.yandex.practicum.filmorate.model.User) with 2 errors: [Field error in object 'user' on field 'email': rejected value [email3email.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@307c95fd,.*]; default message [must be a well-formed email address]] [Field error in object 'user' on field 'birthday': rejected value [null]; codes [NotNull.user.birthday,NotNull.birthday,NotNull.java.time.LocalDate,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.birthday,birthday]; arguments []; default message [birthday]]; default message [must not be null]] "
}

2023-02-18 19:56 UTC, EvgenyKoptubenko requested changes
Есть несколько замечаний. Поправь, пожалуйста.

2023-02-20 21:56 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        Film film = jdbcTemplate.query(sqlSelectFilm, new FilmRowMapper(), filmId).stream()
Сделал, но по итогу не понял как красиво этот запрос обработать, чтобы извлечь из него все данные одной строкой. Пришлось обрабатывать несколько строк с полученными фильмами, отличающиеся только жанрами и юзерами, поставившими лайк. Group by по id фильма тут не подойдёт, иначе другие данные от фильма пропадут ведь. Count тоже поскольку мы считаем не количество, а конкретные id и жанры. По устранению замечания мне не смогли дать совет в чате группы, в том числе наставник. Если можешь подсказать, как должен был выглядеть этот запрос иначе, чтобы его можно было проще обработать, то было бы здорово.

2023-02-20 21:57 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                .orElseThrow(() -> new NullPointerException("Фильм с ID=" + filmId + " отсутствует в базе"));
Создал ArgumentNotFoundException для таких случаев.

2023-02-20 21:58 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Override
Исправил. Добавил сравнение по id фильма, если проверка по количеству лайков дала 0.

2023-02-20 21:59 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/GenreDbStorage.java
> +                    "INSERT INTO genre_list (genre_id, film_id) " +
Сделал

2023-02-20 22:00 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            String sqlSelectName =
Сделал

2023-02-20 22:01 UTC, Truel0ve commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                jdbcTemplate.update(sqlDeleteFilm, film.getId());
Вообще у меня в структуре базы каскадом удаляется всё, что связано с id фильма. Поэтому при удалении фильма, его жанры автоматически также удаляются. Но я включил на всякий случай ещё удаление жанров в метод. А так это по идее взаимозаменяемые вещи.

2023-02-20 22:03 UTC, Truel0ve commented
Сделал обработку при получении DataIntegrityViolationException

2023-02-21 19:41 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-21 19:57 UTC, merged